# Generated by Django 4.2.30 on 2026-07-04 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cognome', models.CharField(max_length=100, verbose_name='Cognome')),
                ('data_nascita', models.DateField(blank=True, null=True, verbose_name='Data di nascita')),
                ('biografia', models.TextField(blank=True, verbose_name='Biografia')),
            ],
            options={
                'verbose_name': 'Autore',
                'verbose_name_plural': 'Autori',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo')),
                ('anno_pubblicazione', models.IntegerField(verbose_name='Anno di pubblicazione')),
                ('isbn', models.CharField(blank=True, help_text='Codice ISBN a 13 cifre (opzionale)', max_length=13, unique=True, verbose_name='ISBN')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('disponibile', models.BooleanField(default=True, verbose_name='Disponibile')),
                ('data_aggiunta', models.DateTimeField(auto_now_add=True, verbose_name='Aggiunto il')),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libri', to='catalogo.autore', verbose_name='Autore')),
                ('categorie', models.ManyToManyField(blank=True, related_name='libri', to='catalogo.categoria', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libri',
                'ordering': ['titolo'],
            },
        ),
    ]
