# Generated by Django 6.0.6 on 2026-07-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='cover_url',
            field=models.URLField(default='immagini/libro_default.png', max_length=300),
        ),
    ]
