# Generated by Django 6.0.6 on 2026-07-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_libro_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(blank=True, help_text='Codice ISBN a 13 cifre (opzionale)', max_length=13, verbose_name='ISBN'),
        ),
    ]
